[workspace]
authors = ["yipy0005 <yipy0005@gmail.com>"]
channels = ["conda-forge"]
name = "ml_book"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.7.6,<10"
